[tool.poetry]
name = "pythonproject-kurs-2"
version = "0.1.0"
description = ""
authors = ["Aleksandr <feat9999@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
